##################################################################################
#
# Laravel API Response Builder Scrutinizer-CI config file
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2019 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

filter:
  excluded_paths: [tests/*]
checks:
  php:
    code_rating: true
#    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
#    fix_identation_4spaces: true
#    fix_doc_comments: true
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
