##################################################################################
#
# Laravel API Response Builder
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2017 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
#  - phpenv config-rm xdebug.ini
  - cp -f "travis/composer-${LARAVEL_VERSION}.json" composer.json
  - FLAGS="--prefer-dist"
  - composer install ${FLAGS}

script:
  - phpunit --configuration phpunit.xml --coverage-clover /tmp/coverage.xml

after_success:
  - vendor/bin/codacycoverage clover /tmp/coverage.xml

