##################################################################################
#
# Laravel API Response Builder
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2017 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

# PHP versions to test package against
php:
  # using major version aliases
  - 5.5
#  - 5.6
#  - 7.0
  - 7.1
#  - hhvm

env:
  - LARAVEL_VERSION="5.1"
  - LARAVEL_VERSION="5.2"
  - LARAVEL_VERSION="5.3"
  - LARAVEL_VERSION="5.4"

matrix:
  exclude:
    - php: 5.5
      env: LARAVEL_VERSION="5.3"
    - php: 5.5
      env: LARAVEL_VERSION="5.4"

#before_script:
##  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
#  - phpenv config-rm xdebug.ini
#  - flags="--prefer-dist"
#  - composer install $flags

# omitting "script:" will default to phpunit
script:
#  - phpunit --configuration phpunit.xml --coverage-clover /tmp/coverage.xml
  - echo $(phpenv version-name)
  - echo ${LARAVEL_VERSION}

#after_script:
#  - vendor/bin/codacycoverage clover /tmp/coverage.xml
