##################################################################################
#
# Laravel API Response Builder
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2017 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

# PHP versions to test package agains
php:
  # using major version aliases
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - flags="--prefer-dist"
  - composer install $flags

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit.xml --coverage-text
