##################################################################################
#
# Laravel API Response Builder Travis CI config file
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinorlowski (.) com>
# @copyright 2016-2019 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

language: php

# Enforcing Ubuntu Trusty to keep PHP 5.5 support
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
dist: trusty

php:
#  - 5.5
#  - 5.6
#  - 7.0
#  - 7.1
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION="5.1"
  - LARAVEL_VERSION="5.2"
  - LARAVEL_VERSION="5.3"
  - LARAVEL_VERSION="5.4"
  - LARAVEL_VERSION="5.5"
  - LARAVEL_VERSION="5.6"
  - LARAVEL_VERSION="5.7"
  - LARAVEL_VERSION="5.8"
  - LARAVEL_VERSION="6.0"

matrix:
  exclude:
    - php: 5.5
      env: LARAVEL_VERSION="5.3"
    - php: 5.5
      env: LARAVEL_VERSION="5.4"
    - php: 5.5
      env: LARAVEL_VERSION="5.5"
    - php: 5.5
      env: LARAVEL_VERSION="5.6"
    - php: 5.5
      env: LARAVEL_VERSION="5.7"
    - php: 5.5
      env: LARAVEL_VERSION="5.8"
    - php: 5.5
      env: LARAVEL_VERSION="6.0"

    - php: 5.6
      env: LARAVEL_VERSION="5.5"
    - php: 5.6
      env: LARAVEL_VERSION="5.6"
    - php: 5.6
      env: LARAVEL_VERSION="5.7"
    - php: 5.6
      env: LARAVEL_VERSION="5.8"
    - php: 5.6
      env: LARAVEL_VERSION="6.0"

    - php: 7.0
      env: LARAVEL_VERSION="5.6"
    - php: 7.0
      env: LARAVEL_VERSION="5.7"
    - php: 7.0
      env: LARAVEL_VERSION="5.8"
    - php: 7.0
      env: LARAVEL_VERSION="6.0"

    - php: 7.1
      env: LARAVEL_VERSION="6.0"

cache:
  directories:
    - ${HOME}/.composer/cache/files

before_script:
  # Some PHP versions does not feature xdebug so we need to disable the coverage
  - if [ ${TRAVIS_PHP_VERSION} != 7.2 && ${TRAVIS_PHP_VERSION} != 7.3 ]; then phpenv config-rm xdebug.ini ; fi
  - cp -f "travis/composer-${LARAVEL_VERSION}.json" composer.json
  - FLAGS="--prefer-dist"
  - composer install "${FLAGS}"
  # We need to tweak signature so setUp() and tearDown() and strip ": void" otherwise PHP will fail complaining
  # This affects Laravel 5.8+ as they pull recent Orchestra that features method signature changes.
  - "if [ ${LARAVEL_VERSION} == 5.8 ]; then sed -i 's/): void/)/' vendor/orchestra/testbench-core/src/TestCase.php ; fi"
script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover /tmp/coverage.xml

after_success:
#   IF coverage file is generated then upload it to Codacy
  - if [ -f /tmp/coverage.xml ] ; then vendor/bin/codacycoverage clover /tmp/coverage.xml ; fi

