language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - flags="--prefer-dist"
  - composer install $flags

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit.xml --coverage-text
