#
# Laravel API Response Builder
#
# @package   MarcinOrlowski\ResponseBuilder
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2016-2021 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder

name: phpstan

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository...
        uses: actions/checkout@v2

      - name: Installing dependencies...
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: ${{ matrix.php }}
          dev: yes

      - name: Running PHPStan...
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon
          php_version: ${{ matrix.php }}
          memory_limit: 16M
