name: phpunit

on: [push]

jobs:
  build:
    strategy:
      # do not stop the workflow if single run failed
      fail-fast: false
      matrix:
        laravel: [6.0, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 7.0, 8.0]
        php: [7.2, 7.3, 7.4, 8.0]
        exclude:
          # Laravel 8.x requires PHP 7.3+
          - laravel: 8.0
            php: 7.2
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository...
        uses: actions/checkout@v2
      - name: Installing dependencies...
        uses: php-actions/composer@v6
        with:
          version: 2
          php_version: 8.0
          dev: yes

      - name: Running unit tests...
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml

#      - name: Running PHPStan...
#        uses: php-actions/phpstan@v3
#        with:
#          path: "src/"
